apiVersion: v1
kind: Secret
metadata:
  name: question-answering-pull-secret
  namespace: question-answering
  annotations:
    kubernetes.io/service-account.name: question-answering-serviceaccount
data:
  .dockercfg: {{ .Values.pullsecret.PULLSECRET }}
type: dockercfg