apiVersion: v1
kind: Secret
metadata:
  name: question-answering-pull-secret
  namespace: question-answering
data:
  .dockerconfigjson: {{ .Values.pullsecret.PULLSECRET }}
type: kubernetes.io/dockerconfigjson