kind: Deployment
apiVersion: apps/v1
metadata:
  name: question-answering
  namespace: question-answering
  labels:
      app: question-answering
spec:
  selector:
    matchLabels:
      app: question-answering
  replicas: 1
  template:
    metadata:
      labels:
        app: question-answering
    spec:
      containers:
      - name: question-answering
        image: {{ .Values.container_registry.CR }}/{{ .Values.container_registry.CR_REPOSITORY }}/{{ .Values.container_image.CI_NAME }}:{{ .Values.container_image.CI_TAG }}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: ["sh", "-c", "ls"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "ls"]
          initialDelaySeconds: 40
        env:
        - name: QA_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: QA_API_KEY
        - name: DISCOVERY_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: DISCOVERY_API_KEY
        - name: DISCOVERY_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_URL
        - name: DISCOVERY_INSTANCE
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_INSTANCE
        - name: DISCOVERY_PROJECT
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_PROJECT
        - name: DISCOVERY_COLLECTION_ID
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_COLLECTION_ID
        - name: PRIME_QA_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: PRIME_QA_URL
        - name: RERANKER_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: RERANKER_URL
        - name: MAAS_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: MAAS_URL
        - name: MAAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: MAAS_API_KEY
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: PROXY_URL
        - name: PROXY_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: PROXY_API_KEY
        - name: EXPERIMENT_METRICS_SESSION
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_METRICS_SESSION
        - name: EXPERIMENT_LLM_NAME
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_NAME
        - name: EXPERIMENT_LLM_MIN_NEW_TOKENS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MIN_NEW_TOKENS
        - name: EXPERIMENT_LLM_MAX_NEW_TOKENS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MAX_NEW_TOKENS
        - name: EXPERIMENT_LLM_MAX_INPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MAX_INPUT_DOCUMENTS
        - name: EXPERIMENT_LLM_PROMPT
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_PROMPT
        - name: EXPERIMENT_RERANKER_MAX_INPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_MAX_INPUT_DOCUMENTS
        - name: EXPERIMENT_RERANKER_MODEL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_MODEL    
        - name: EXPERIMENT_RERANKER_ID
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_ID    
        - name: EXPERIMENT_DISCOVERY_MAX_OUTPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_MAX_OUTPUT_DOCUMENTS
        - name: EXPERIMENT_DISCOVERY_CHARACTERS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_CHARACTERS
        - name: EXPERIMENT_DISCOVERY_FIND_ANSWERS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_FIND_ANSWERS
        - name: EXPERIMENT_METRICS_DIRECTORYS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_METRICS_DIRECTORYS           
        ports:
        - containerPort: 8080
      serviceAccountName: {{ .Values.serviceAccountPatch.metadata.name }}
      imagePullSecrets:
      - name: question-answering-pull-secret
      securityContext:
      - allowPrivilegeEscalation: false 
      restartPolicy: Always
