kind: Deployment
apiVersion: apps/v1
metadata:
  name: question-answering
  namespace: question-answering
  labels:
      app: question-answering
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
spec:
  selector:
    matchLabels:
      app: question-answering
  replicas: 1
  template:
    metadata:
      labels:
        app: question-answering
    spec:
      containers:
      - name: question-answering
        image: {{ .Values.container_registry.CR }}/{{ .Values.container_registry.CR_REPOSITORY }}/{{ .Values.container_image.CI_NAME }}:{{ .Values.container_image.CI_TAG }}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: ["sh", "-c", "ls"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl http://localhost:8080/p/health"]
          initialDelaySeconds: 40
        env:
        - name: QA_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: QA_API_KEY
        - name: DISCOVERY_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: DISCOVERY_API_KEY
        {{- if .Values.elastic.ELASTIC_SEARCH_URL }}
        - name: ELASTIC_SEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: ELASTIC_SEARCH_URL
        {{- end }}
        {{- if .Values.elastic.ELASTIC_SEARCH_INDEX }}
        - name: ELASTIC_SEARCH_INDEX
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: ELASTIC_SEARCH_INDEX
        {{- end }}
        {{- if .Values.elastic.ELASTIC_SEARCH_PASSWORD }}
        - name: ELASTIC_SEARCH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: ELASTIC_SEARCH_PASSWORD
        {{- end }}
        {{- if .Values.elastic.ELASTIC_SEARCH_USER }}
        - name: ELASTIC_SEARCH_USER 
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: ELASTIC_SEARCH_USER 
        {{- end }}
        {{- if .Values.discovery.DISCOVERY_URL }}
        - name: DISCOVERY_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_URL
        {{- end }}
        {{- if .Values.discovery.DISCOVERY_INSTANCE }}
        - name: DISCOVERY_INSTANCE
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_INSTANCE
        {{- end }}
        {{- if .Values.discovery.DISCOVERY_PROJECT }}
        - name: DISCOVERY_PROJECT
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_PROJECT
        {{- end }}
        {{- if .Values.discovery.DISCOVERY_COLLECTION_ID }}
        - name: DISCOVERY_COLLECTION_ID
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: DISCOVERY_COLLECTION_ID
        {{- end }}
        {{- if .Values.prime_qa.PRIME_QA_URL }}
        - name: PRIME_QA_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: PRIME_QA_URL
        {{- end }}
        {{- if .Values.reranker.RERANKER_URL }}
        - name: RERANKER_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: RERANKER_URL
        {{- end }}
        {{- if .Values.maas.MAAS_URL }}
        - name: MAAS_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: MAAS_URL
        {{- end }}
        - name: MAAS_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: MAAS_API_KEY
        {{- if .Values.proxy.MAAS_URL }}
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: PROXY_URL
        {{- end }}       
        - name: PROXY_API_KEY
          valueFrom:
            secretKeyRef:
              name: question-answering-secrets
              key: PROXY_API_KEY
        {{- if .Values.experiment.EXPERIMENT_METRICS_SESSION }}
        - name: EXPERIMENT_METRICS_SESSION
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_METRICS_SESSION
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_LLM_NAME }} 
        - name: EXPERIMENT_LLM_NAME
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_NAME
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_LLM_MIN_NEW_TOKENS }} 
        - name: EXPERIMENT_LLM_MIN_NEW_TOKENS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MIN_NEW_TOKENS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_LLM_MAX_NEW_TOKENS }} 
        - name: EXPERIMENT_LLM_MAX_NEW_TOKENS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MAX_NEW_TOKENS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_LLM_MAX_INPUT_DOCUMENTS }} 
        - name: EXPERIMENT_LLM_MAX_INPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_MAX_INPUT_DOCUMENTS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_LLM_PROMPT }}         
        - name: EXPERIMENT_LLM_PROMPT
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_LLM_PROMPT
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_RERANKER_MAX_INPUT_DOCUMENTS }}
        - name: EXPERIMENT_RERANKER_MAX_INPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_MAX_INPUT_DOCUMENTS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_RERANKER_MODEL }}
        - name: EXPERIMENT_RERANKER_MODEL
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_MODEL
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_RERANKER_ID }}
        - name: EXPERIMENT_RERANKER_ID
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_RERANKER_ID
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_DISCOVERY_MAX_OUTPUT_DOCUMENTS }}
        - name: EXPERIMENT_DISCOVERY_MAX_OUTPUT_DOCUMENTS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_MAX_OUTPUT_DOCUMENTS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_DISCOVERY_CHARACTERS }}       
        - name: EXPERIMENT_DISCOVERY_CHARACTERS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_CHARACTERS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_DISCOVERY_FIND_ANSWERS }} 
        - name: EXPERIMENT_DISCOVERY_FIND_ANSWERS
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_DISCOVERY_FIND_ANSWERS
        {{- end }}
        {{- if .Values.experiment.EXPERIMENT_METRICS_DIRECTORY }} 
        - name: EXPERIMENT_METRICS_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: question-answering-confmap
              key: EXPERIMENT_METRICS_DIRECTORY 
        {{- end }}          
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false 
      serviceAccountName: question-answering-serviceaccount
      imagePullSecrets:
      - name: question-answering-pull-secret
      restartPolicy: Always
