apiVersion: v1
kind: Secret
metadata:
  name: question-answering-secrets
  namespace: question-answering
type: Opaque
stringData:  
  QA_API_KEY: {{ .Values.qa.QA_API_KEY }}
  DISCOVERY_API_KEY: {{ .Values.discovery.DISCOVERY_API_KEY }}
  MAAS_API_KEY: {{ .Values.maas.MAAS_API_KEY }}
  PROXY_API_KEY: {{ .Values.proxy.PROXY_API_KEY }}